<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Sprint 3b — automation depth.
     * A demande is an inbound interest signal captured from a campaign or sequence interaction.
     * All FK references are nullable SET NULL so a demande is never orphaned by a parent delete.
     *
     * FK on-delete:
     *   contact_id      → contacts       SET NULL (survives contact deletion / GDPR erasure)
     *   campaign_id     → campaigns      SET NULL (attribution preserved as metadata)
     *   campaign_run_id → campaign_runs  SET NULL (attribution preserved as metadata)
     *   sequence_id     → sequences      SET NULL (attribution preserved as metadata)
     *
     * Indexes:
     *   contact_id             — reverse lookup: all demandes for a contact
     *   (status, captured_at)  — hot path: dashboard / filter by status+date
     *   campaign_id            — reverse lookup: demandes generated by a campaign
     *
     * Engine: InnoDB.
     */
    public function up(): void
    {
        Schema::create('demandes', function (Blueprint $table) {
            $table->id();

            $table->unsignedBigInteger('contact_id')->nullable();
            $table->unsignedBigInteger('campaign_id')->nullable();
            $table->unsignedBigInteger('campaign_run_id')->nullable();
            $table->unsignedBigInteger('sequence_id')->nullable();

            // kind: free-form classification (e.g. 'rfq', 'info', 'callback')
            $table->string('kind', 32)->nullable();

            // status: pending|in_review|accepted|rejected
            $table->string('status', 16)->default('pending');

            $table->text('notes')->nullable();

            // captured_at: datetime (not timestamp) per v3 spec — avoids 2038 overflow
            $table->datetime('captured_at');

            $table->timestamps();

            // ── Foreign keys ──────────────────────────────────────────────────────
            $table->foreign('contact_id')
                  ->references('id')->on('contacts')
                  ->nullOnDelete();

            $table->foreign('campaign_id')
                  ->references('id')->on('campaigns')
                  ->nullOnDelete();

            $table->foreign('campaign_run_id')
                  ->references('id')->on('campaign_runs')
                  ->nullOnDelete();

            $table->foreign('sequence_id')
                  ->references('id')->on('sequences')
                  ->nullOnDelete();

            // ── Indexes ───────────────────────────────────────────────────────────
            $table->index('contact_id');
            $table->index(['status', 'captured_at']);
            $table->index('campaign_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('demandes');
    }
};
