<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * AI translation — stores per-language variants of campaign templates.
     * One row per (template, language) pair. FR base stays on campaign_templates;
     * this table holds translated variants (e.g. EN).
     */
    public function up(): void
    {
        Schema::create('campaign_template_translations', function (Blueprint $table) {
            $table->id();

            $table->foreignId('campaign_template_id')
                  ->constrained()
                  ->cascadeOnDelete();

            // BCP-47 / ISO-639-1 code, max 8 chars (e.g. 'en', 'de', 'es')
            $table->string('language', 8);

            $table->string('subject', 255);

            // Full HTML body — longText to accommodate rich layouts
            $table->longText('html_content');

            $table->string('preview_text', 255)->nullable();

            // true  = generated by AI (may need review)
            // false = manually edited by a user
            $table->boolean('is_ai_generated')->default(true);

            // Non-null when a user explicitly marked this translation as reviewed.
            // Advisory only — does not gate sending.
            $table->timestamp('reviewed_at')->nullable();

            // MD5 hashes of the source (FR) fields at translation time.
            // Used to detect staleness: if the base changes, these diverge.
            // Each field coalesced to '' before hashing (ConvertEmptyStringsToNull
            // persists empty preview as NULL; both snapshot and check normalize).
            $table->string('src_subject_hash', 32)->nullable();
            $table->string('src_preview_hash', 32)->nullable();
            $table->string('src_body_hash', 32)->nullable();

            $table->timestamps();

            // One translation row per template per language
            // Explicit short index name (auto-generated name exceeds MySQL 64-char limit).
            $table->unique(['campaign_template_id', 'language'], 'ctt_template_lang_unique');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('campaign_template_translations');
    }
};
